[package]
name = "ssh_standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
pcap = "0.8.1"
regex = "1.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
ssh-parser = "0.5.0"