[package]
name = "test_ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.23", features = ["derive"] }
env_logger = "0.8.4"
retina-core = { path = "../../core" }
retina-filtergen = { path = "../../filtergen" }
serde_json = "1.0.96"