[package]
name = "test_ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
retina-core = { path = "../../core" }
retina-filtergen = { path = "../../filtergen" }
retina-datatypes = { path = "../../datatypes" }
serde = { version = "1.0", features = ["derive"] }